/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountAvatar: typeof import('./src/components/AccountAvatar.vue')['default']
    AccountBalanceCards: typeof import('./src/components/AccountBalanceCards.vue')['default']
    AccountForm: typeof import('./src/components/AccountForm.vue')['default']
    AccountSelectorSheet: typeof import('./src/components/AccountSelectorSheet.vue')['default']
    AddTransactionForm: typeof import('./src/components/AddTransactionForm.vue')['default']
    AmountEntrySheet: typeof import('./src/components/AmountEntrySheet.vue')['default']
    AppShell: typeof import('./src/components/AppShell.vue')['default']
    BarChart: typeof import('./src/components/BarChart.vue')['default']
    BottomSheet: typeof import('./src/components/BottomSheet.vue')['default']
    CategoryAvatar: typeof import('./src/components/CategoryAvatar.vue')['default']
    CategoryChip: typeof import('./src/components/CategoryChip.vue')['default']
    CategoryForm: typeof import('./src/components/CategoryForm.vue')['default']
    CategorySelector: typeof import('./src/components/CategorySelector.vue')['default']
    ConfirmDeleteSheet: typeof import('./src/components/ConfirmDeleteSheet.vue')['default']
    DashboardHeader: typeof import('./src/components/DashboardHeader.vue')['default']
    DonutChart: typeof import('./src/components/DonutChart.vue')['default']
    DonutChartTabs: typeof import('./src/components/DonutChartTabs.vue')['default']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    EquityCard: typeof import('./src/components/EquityCard.vue')['default']
    FAB: typeof import('./src/components/FAB.vue')['default']
    FilterChip: typeof import('./src/components/FilterChip.vue')['default']
    FormField: typeof import('./src/components/FormField.vue')['default']
    IconPicker: typeof import('./src/components/IconPicker.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    PartySelector: typeof import('./src/components/PartySelector.vue')['default']
    ReconcileSheet: typeof import('./src/components/ReconcileSheet.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SegmentedControl: typeof import('./src/components/SegmentedControl.vue')['default']
    SelectTrigger: typeof import('./src/components/SelectTrigger.vue')['default']
    SummaryStrip: typeof import('./src/components/SummaryStrip.vue')['default']
    SyncBadge: typeof import('./src/components/SyncBadge.vue')['default']
    SyncErrorsSheet: typeof import('./src/components/SyncErrorsSheet.vue')['default']
    SyncIndicator: typeof import('./src/components/SyncIndicator.vue')['default']
    Toggle: typeof import('./src/components/Toggle.vue')['default']
    TransactionCard: typeof import('./src/components/TransactionCard.vue')['default']
    TransactionFilterSheet: typeof import('./src/components/TransactionFilterSheet.vue')['default']
  }
}
