/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddTransactionForm: typeof import('./src/components/AddTransactionForm.vue')['default']
    AppShell: typeof import('./src/components/AppShell.vue')['default']
    CategoryForm: typeof import('./src/components/CategoryForm.vue')['default']
    CategorySelector: typeof import('./src/components/CategorySelector.vue')['default']
    FAB: typeof import('./src/components/FAB.vue')['default']
    IconPicker: typeof import('./src/components/IconPicker.vue')['default']
    PartySelector: typeof import('./src/components/PartySelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SyncIndicator: typeof import('./src/components/SyncIndicator.vue')['default']
    TransactionCard: typeof import('./src/components/TransactionCard.vue')['default']
  }
}
